version: 2.1

executors:
  main:
    docker:
      - image: circleci/node:lts-browsers

jobs:
  install_dependencies:
    executor: main
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Authenticate with registry
          command: echo "@utilitywarehouse:registry=https://registry.npmjs.org/\n//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Install dependencies
          command: make install-ci
      - save_cache:
          name: Save Yarn package cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ~/repo/.npmrc
  lint:
    executor: main
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: make install-ci
      - run:
          name: Run linter
          command: make lint
  test:
    executor: main
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: make install-ci
      - run:
          name: Run automated tests
          command: make test
  build:
    executor: main
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: make install-ci
      - run:
          name: Build
          command: make build
  build-and-publish:
    executor: main
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: make install-ci
      - run:
          name: Build
          command: make build
      - run:
          name: Publish
          command: make publish

workflows:
  main:
    jobs:
      - install_dependencies
      - lint:
          requires:
            - install_dependencies
      - test:
          requires:
            - install_dependencies
      - build:
          filters:
            branches:
              ignore:
                - master
                - alpha
          requires:
            - lint
            - test
      - build-and-publish:
          filters:
            branches:
              only:
                - master
                - alpha
          requires:
            - lint
            - test
