version: 2.1

executors:
  main:
    docker:
      - image: circleci/node:lts-browsers

jobs:
  install_dependencies:
    executor: main
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Authenticate with registry
          command: printf "@utilitywarehouse:registry=https://registry.npmjs.org/\n//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/project/.npmrc
      - run:
          name: Install dependencies
          command: yarn install:ci
      - save_cache:
          name: Save Yarn package cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - save_cache:
          name: Save registry authentication cache
          key: registry-authentication
          paths:
            - ~/project/.npmrc

  lint:
    executor: main
    steps:
      - checkout
      - restore_cache:
          keys:
            - registry-authentication
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install:ci
      - run:
          name: Run linter
          command: yarn lint
  packages-changed:
    executor: main
    steps:
      - checkout
      - restore_cache:
          keys:
            - registry-authentication
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install:ci
      - run:
          name: On packages changed
          command: |
            export PR_NUMBER=$(node ./scripts/get-pr-number.js)
            yarn ci-package-changed
  build:
    executor: main
    steps:
      - checkout
      - restore_cache:
          keys:
            - registry-authentication
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install:ci
      - run:
          name: Build
          command: yarn build
  build-and-publish:
    executor: main
    steps:
      - checkout
      - restore_cache:
          keys:
            - registry-authentication
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install:ci
      - run:
          name: Build
          command: yarn build
      - run:
          name: Publish
          command: yarn publish

workflows:
  main:
    jobs:
      - install_dependencies
      - lint:
          requires:
            - install_dependencies
      - packages-changed:
          requires:
            - install_dependencies
      - build:
          filters:
            branches:
              ignore:
                - alpha
          requires:
            - lint
      - build-and-publish:
          filters:
            branches:
              only:
                - alpha
          requires:
            - lint
