name: Build and Commit Design Tokens Changes

on:
  pull_request:
    types: [opened, reopened]
    paths:
      - 'packages/design-tokens/**'

permissions:
  contents: write

jobs:
  build_and_commit:
    runs-on: ubuntu-latest

    steps:
      - name: 🏗 Setup repo
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: 🏗 Checkout
        uses: actions/checkout@v4

      - name: 🏗 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: 📦 Install dependencies
        run: pnpm install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: 🏗 Build Design Tokens
        working-directory: ./packages/design-tokens
        run: pnpm build

      - name: 📝 Commit Built Files
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'
          git add -A
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m 'Build design tokens output'
          fi

      - name: 🚀 Push Changes
        run: |
          git push origin HEAD:${{ github.head_ref }}

      - name: 🔍 Run Checks
        run: pnpm checks
