name: Code Checks
on: push
jobs:
  checks:
    name: Code Checks
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    steps:
    - uses: pnpm/action-setup@v2
      with:
        version: 7
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '18.x'
        registry-url: 'https://registry.npmjs.org'
        cache: 'pnpm'
    - run: pnpm install
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - run: pnpm run checks
