name: Code Checks
on: [push]

jobs:
  checks:
    name: Code Checks
    runs-on: ubuntu-latest
    steps:
    - uses: pnpm/action-setup@v2
      with:
        version: 6
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        registry-url: 'https://registry.npmjs.org'
        cache: 'pnpm'

    - run: pnpm install
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - run: pnpm lint:ci
    - run: pnpm build
