name: Code Checks
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  checks:
    name: Code Checks
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    steps:
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
      - run: pnpm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: Run checks for branch
        run: pnpm checks --filter="...[${{ steps.extract_branch.outputs.branch }}]"
        if: ${{ github.event_name == 'pull_request' }}
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
      - name: Run checks
        run: pnpm run checks
        if: ${{ github.event_name == 'push' }}
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
