name: Customer UI Storybook
on:
  push:
    paths:
      - 'packages/material/**'

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
    - uses: pnpm/action-setup@v2
      with:
        version: 7
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        registry-url: 'https://registry.npmjs.org'
        cache: 'pnpm'

    - run: pnpm install
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Publish to Chromatic
      uses: chromaui/action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        buildScriptName: 'storybook:build'
        workingDir: 'packages/material'
        exitOnceUploaded: true
        exitZeroOnChanges: true


