name: Deploy Storybook
on: push
# on:
#   push:
#     tags:
#       - '*'
jobs:
  deploy:
    name: Deploy Storybook
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build & Push Docker Image
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} registry.uw.systems
        docker build . -t registry.uw.systems/${{ secrets.DOCKER_REPOSITORY_NAMESPACE }}/cwui-storybook:release --build-arg NPM_TOKEN=$(NPM_TOKEN)
        docker push -a registry.uw.systems/${{ secrets.DOCKER_REPOSITORY_NAMESPACE }}/cwui-storybook
