name: Native UI Previews

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'packages/native-ui/**'
      - 'apps/native-ui-storybook/**'
  push:
    branches:
      - main
    paths:
      - 'packages/native-ui/**'
      - 'apps/native-ui-storybook/**'

env:
  CI: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - platform: android
            os: macos-13-large
            build_command: build:preview:android
            app_file: ./apps/native-ui-storybook/build/native-ui.apk
            env_file: .env.android
            appetize_platform: android
            api_key_env: ANDROID_API_KEY
            build_artifact: native-ui.apk
          - platform: ios
            os: macos-13-xlarge
            build_command: build:preview:ios
            app_file: ./apps/native-ui-storybook/build/native-ui.tar.gz
            env_file: .env.ios
            appetize_platform: ios
            api_key_env: IOS_API_KEY
            build_artifact: native-ui.tar.gz

    name: Build for ${{ matrix.platform | title }}
    concurrency:
      group: preview-${{ matrix.platform }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: 🔍 Check if ${{ matrix.platform }} build should be skipped
        id: check_skip
        run: |
          SKIP=false
          if [ "${{ github.event_name }}" == "push" ]; then
            if [[ "${{ github.event.head_commit.message }}" == *"[skip-${{ matrix.platform }}]"* ]] || [[ "${{ github.event.head_commit.message }}" == *"[skip-native]"* ]]; then
              SKIP=true
            fi
          elif [ "${{ github.event_name }}" == "pull_request" ]; then
            if [[ "${{ github.event.pull_request.title }}" == *"[skip-${{ matrix.platform }}]"* ]] || [[ "${{ github.event.pull_request.title }}" == *"[skip-native]"* ]] || [[ "${{ github.event.pull_request.body }}" == *"[skip-${{ matrix.platform }}]"* ]] || [[ "${{ github.event.pull_request.body }}" == *"[skip-native]"* ]]; then
              SKIP=true
            fi
          fi
          echo "skip=$SKIP" >> "$GITHUB_OUTPUT"

      - name: 🔧 Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
        if: steps.check_skip.outputs.skip == 'false'

      - name: 📂 Checkout code
        uses: actions/checkout@v3
        if: steps.check_skip.outputs.skip == 'false'

      - name: 🔧 Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
        if: steps.check_skip.outputs.skip == 'false'

      - name: ☕ Setup Java
        if: matrix.platform == 'android' && steps.check_skip.outputs.skip == 'false'
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17.0.10'
          java-package: jdk
          architecture: x64

      - name: 🍏 Setup Xcode
        if: matrix.platform == 'ios' && steps.check_skip.outputs.skip == 'false'
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2.0'

      - name: 🔧 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: ${{ matrix.platform == 'android' && 'latest' || '9.2.0' }}
          token: ${{ secrets.EXPO_TOKEN }}
        if: steps.check_skip.outputs.skip == 'false'

      - name: 📦 Install dependencies
        run: pnpm install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: steps.check_skip.outputs.skip == 'false'

      - name: 🔄 Restore .env
        if: steps.check_skip.outputs.skip == 'false' && (github.event.action == 'synchronize' || github.event_name == 'push') && matrix.platform == 'android'
        working-directory: ./apps/native-ui-storybook
        run: |
          GITHUB_PAT_TOKEN=${{ secrets.DS_ACTION_READ_PAT }} ARTIFACT_NAME=${{ github.event.pull_request.base.sha }}-env-${{ matrix.platform }} node ./scripts/getArtifacts.js

      - name: 🍎 Build ${{ matrix.platform | title }} app
        run: pnpm run ${{ matrix.build_command }}
        working-directory: ./apps/native-ui-storybook
        if: steps.check_skip.outputs.skip == 'false'

      - name: 🔐 Create/Read .env
        run: touch ./apps/native-ui-storybook/${{ matrix.env_file }} && cat ./apps/native-ui-storybook/${{ matrix.env_file }}
        if: steps.check_skip.outputs.skip == 'false'

      - name: 🔄 Load .env file
        uses: xom9ikk/dotenv@v2
        with:
          path: ./apps/native-ui-storybook
          mode: ${{ matrix.platform }}
        if: steps.check_skip.outputs.skip == 'false'

      - name: ⬆️ Upload new bundle to Appetize
        uses: appetizeio/github-action-appetize@v1.0.1
        id: appetizeio_github_action_appetize
        with:
          apiToken: ${{ secrets.APPETIZE_API_TOKEN }}
          appFile: ${{ matrix.app_file }}
          platform: ${{ matrix.appetize_platform }}
        if: |
          steps.check_skip.outputs.skip == 'false' && (
            github.event.action == 'opened' ||
            github.event.action == 'reopened' ||
            (!env[${{ matrix.api_key_env }}] && github.event_name == 'pull_request')
          )

      - name: 📝 Add output to .env
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "${{ matrix.api_key_env }}=${{ secrets['APPETIZE_PUBLIC_KEY_' | append: matrix.platform | upper ] }}" >> ./apps/native-ui-storybook/${{ matrix.env_file }}
          elif [ "${{ steps.appetizeio_github_action_appetize.outputs.publicKey }}" ]; then
            echo "${{ matrix.api_key_env }}=${{ steps.appetizeio_github_action_appetize.outputs.publicKey }}" >> ./apps/native-ui-storybook/${{ matrix.env_file }}
          else
            echo "No public key found"
          fi
        if: |
          steps.check_skip.outputs.skip == 'false' && (
            github.event.action == 'opened' || 
            github.event.action == 'reopened' || 
            !env[${{ matrix.api_key_env }}]
          )
        working-directory: ./apps/native-ui-storybook

      - name: 🔄 Reload .env file
        uses: xom9ikk/dotenv@v2
        with:
          path: ./apps/native-ui-storybook
          mode: ${{ matrix.platform }}
        if: steps.check_skip.outputs.skip == 'false'

      - name: 💾 Save .env
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.pull_request.base.sha }}-env-${{ matrix.platform }}
          path: ./apps/native-ui-storybook/${{ matrix.env_file }}
          include-hidden-files: true
          overwrite: true
        if: steps.check_skip.outputs.skip == 'false' && github.event_name == 'pull_request' && env[${{ matrix.api_key_env }}]

      - name: ⬆️ Upload updated bundle to Appetize
        uses: appetizeio/github-action-appetize@v1.0.1
        with:
          apiToken: ${{ secrets.APPETIZE_API_TOKEN }}
          publicKey: ${{ env[matrix.api_key_env] }}
          appFile: ${{ matrix.app_file }}
          platform: ${{ matrix.appetize_platform }}
        if: steps.check_skip.outputs.skip == 'false' && github.event.action != 'opened' && env[matrix.api_key_env]

  build-for-web:
    name: Build for Web
    runs-on: ubuntu-latest
    needs: build
    if: ${{ !contains(needs.build.*.result, 'failure') }}
    concurrency:
      group: preview-web-${{ github.ref }}
      cancel-in-progress: true
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - name: 🔧 Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: 📂 Checkout code
        uses: actions/checkout@v4

      - name: 🔧 Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: 🔍 Extract branch name
        id: extract_branch
        shell: bash
        run: echo "branch=$(echo ${GITHUB_HEAD_REF##*/})" >> "$GITHUB_OUTPUT"

      - name: 📦 Install dependencies
        run: pnpm install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: 📦 Install Vercel CLI
        run: pnpm install --global vercel@latest

      - name: 🔄 Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: 📝 Log commit message and PR details
        run: |
          echo "Commit message: ${{ github.event.head_commit.message }}"
          echo "PR Title: ${{ github.event.pull_request.title }}"
          echo "PR Body: ${{ github.event.pull_request.body }}"

      # Restore and load .env files for Android and iOS
      - name: 🔄 Restore and Load .env for Android
        if: !contains(github.event.pull_request.title , '[skip-android]') && !contains(github.event.pull_request.body, '[skip-android]') && !contains(github.event.pull_request.title, '[skip-native]') && !contains(github.event.pull_request.body, '[skip-native]')
        working-directory: ./apps/native-ui-storybook
        run: |
          GITHUB_PAT_TOKEN=${{ secrets.DS_ACTION_READ_PAT }} ARTIFACT_NAME=${{ github.event.pull_request.base.sha }}-env-android node ./scripts/getArtifacts.js
          echo "ANDROID_API_KEY=${{ env.ANDROID_API_KEY }}" >> .env
        uses: xom9ikk/dotenv@v2
        with:
          path: ./apps/native-ui-storybook
          mode: 'android'

      - name: 🔄 Restore and Load .env for iOS
        if: !contains(github.event.pull_request.title , '[skip-ios]') && !contains(github.event.pull_request.body, '[skip-ios]') && !contains(github.event.pull_request.title, '[skip-native]') && !contains(github.event.pull_request.body, '[skip-native]')
        working-directory: ./apps/native-ui-storybook
        run: |
          GITHUB_PAT_TOKEN=${{ secrets.DS_ACTION_READ_PAT }} ARTIFACT_NAME=${{ github.event.pull_request.base.sha }}-env-ios node ./scripts/getArtifacts.js
          echo "IOS_API_KEY=${{ env.IOS_API_KEY }}" >> .env
        uses: xom9ikk/dotenv@v2
        with:
          path: ./apps/native-ui-storybook
          mode: 'ios'

      - name: 🔐 Create local production .env
        if: |
          github.event_name == 'push' || 
          (
            github.event_name != 'push' && (
              contains(github.event.pull_request.title, '[skip-android]') ||
              contains(github.event.pull_request.body, '[skip-android]') ||
              contains(github.event.pull_request.title, '[skip-ios]') ||
              contains(github.event.pull_request.body, '[skip-ios]') ||
              contains(github.event.pull_request.title, '[skip-native]') ||
              contains(github.event.pull_request.body, '[skip-native]')
            )
          )
        working-directory: ./apps/native-ui-storybook
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "ANDROID_API_KEY=${{ secrets.APPETIZE_PUBLIC_KEY_ANDROID }}" >> .env
            echo "IOS_API_KEY=${{ secrets.APPETIZE_PUBLIC_KEY_IOS }}" >> .env
          elif [[ "${{ github.event.pull_request.title }}" == *"[skip-native]"* || "${{ github.event.pull_request.body }}" == *"[skip-native]"* ]]; then
            echo "ANDROID_API_KEY=${{ secrets.APPETIZE_PUBLIC_KEY_ANDROID }}" >> .env
            echo "IOS_API_KEY=${{ secrets.APPETIZE_PUBLIC_KEY_IOS }}" >> .env
          elif [[ "${{ github.event.pull_request.title }}" == *"[skip-ios]"* || "${{ github.event.pull_request.body }}" == *"[skip-ios]"* ]]; then
            echo "ANDROID_API_KEY=${{ env.ANDROID_API_KEY }}" >> .env
          elif [[ "${{ github.event.pull_request.title }}" == *"[skip-android]"* || "${{ github.event.pull_request.body }}" == *"[skip-android]"* ]]; then
            echo "IOS_API_KEY=${{ env.IOS_API_KEY }}" >> .env
          else
            echo "No public key found"
          fi

      - name: 🔄 Pull Vercel Environment Information
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            vercel pull --yes --environment=preview --git-branch=${{ steps.extract_branch.outputs.branch }} --token=${{ secrets.VERCEL_TOKEN }}
          else
            vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          fi

      - name: 🏗 Build Project Artifacts
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            vercel build --token=${{ secrets.VERCEL_TOKEN }}
          else
            vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
          fi

      - name: 🚀 Deploy Project Artifacts to Vercel
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} --meta githubCommitRef=${{ github.head_ref }} --meta githubCommitSha=${{ github.sha }} > ./vercel-deploy.log
          else
            vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} --meta githubCommitSha=${{ github.sha }} > ./vercel-deploy.log
          fi

      - name: 🔍 Extract Deployment URL
        if: github.event_name == 'pull_request'
        id: extract_deployment_url
        run: |
          echo "deployment-url=$(cat ./vercel-deploy.log)" >> "$GITHUB_OUTPUT"

      - name: 💬 Find Comment
        uses: peter-evans/find-comment@v3
        if: github.event_name == 'pull_request'
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Storybook Preview

      - name: 💬 Create or update comment
        uses: peter-evans/create-or-update-comment@v4
        if: github.event_name == 'pull_request'
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## 🖥️ Native UI - Storybook Preview

            Visit the Storybook preview URL to see the changes in action.

            - Preview: [${{ steps.extract_deployment_url.outputs.deployment-url }}](${{ steps.extract_deployment_url.outputs.deployment-url }})

            ## 📱 Appetize Previews

            You can view the apps using the link above and choosing the device from the top action bar. Alternatively, you can use the direct links below.

            - [Android](https://appetize.io/embed/${{ env.ANDROID_API_KEY }})
            - [iOS](https://appetize.io/embed/${{ env.IOS_API_KEY }})

            ---
            Last updated from commit ${{ github.sha }}
          edit-mode: replace
