name: Customer UI Storybook
on:
  push:
    paths:
      - 'packages/material/**'

jobs:
  preview:
    name: Deployment Preview
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        registry-url: 'https://registry.npmjs.org'
        cache: 'yarn'
        cache-dependency-path: |
          package.json
          'packages/**/package.json'

    - run: yarn install:ci
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Deploy Storybook Preview
      run: yarn storybook:deploy


